- type: job
  id: CEBard
  setPreference: true
  name: ce-job-name-bard
  description: ce-job-desc-bard
  playTimeTracker: CEJobBard
  #startingGear: CEGuardGear
  icon: CEJobIconBard
  supervisors: ce-job-supervisors-empire
  canBeAntag: true

#- type: startingGear
#  id: CEGuardGear
#  equipment:
#    keys: CEKeyRingGuard
#    belt: CEWalletFilledTest
