- type: department
  id: CEGuard
  name: department-CEGuard
  description: department-CEGuard-desc
  weight: 9
  color: "#576384"
  editorHidden: false
  roles:
  - CEGuardCommander
  - CEInvestigator
  - CEGuard

- type: department
  id: CECitizens
  name: department-CECitizens
  description: department-CECitizens-desc
  weight: 0
  color: "#b3b3b3"
  editorHidden: false
  roles:
  - CETownfolk
  - CEBard
