- type: job
  id: CEGuard
  setPreference: true
  name: ce-job-name-guard
  description: ce-job-desc-guard
  playTimeTracker: CEJobGuard
  startingGear: CEGuardGear
  icon: CEJobIconGuard
  supervisors: ce-job-supervisors-guard-commander
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: CESalaryCounter
        salary: 50

- type: startingGear
  id: CEGuardGear
  equipment:
    belt: CEKeyRingGuard
    belt2: CEGunJustice
    pocket1: CEWalletFilledGuard


- type: entity
  id: CEWalletFilledGuard
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #100cp total
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEKeyRingGuard
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyGuardHall
    - id: CEKeyGuardStaff
