- type: job
  id: CEGuardCommander
  setPreference: true
  name: ce-job-name-guard-commander
  description: ce-job-desc-guard-commander
  playTimeTracker: CEJobGuardCommander
  startingGear: CEGuardCommanderGear
  icon: CEJobIconGuardCommander
  requireAdminNotify: true
  joinNotifyCrew: true
  canBeAntag: false
  supervisors: ce-job-supervisors-empire
  weight: 3
  special:
    - !type:AddComponentSpecial
      components:
      - type: CESalaryCounter
        salary: 200
  #requirements:
  #  - !type:DepartmentTimeRequirement
  #    department: CEGuard
  #    time: 10980 # 3 hours

- type: startingGear
  id: CEGuardCommanderGear
  equipment:
    belt: CEKeyRingGuardCommander
    belt2: CEGunJustice
    pocket1: CEWalletFilledGuardCommander

- type: entity
  id: CEWalletFilledGuardCommander
  parent: CEWallet
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents: #200cp total
    - id: CECoinGold1
    - id: CECoinSilver5
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinSilver1
    - id: CECoinCopper10

- type: entity
  id: CEKeyRingGuardCommander
  parent: CEBaseKeyRing
  categories: [ HideSpawnMenu ]
  components:
  - type: StorageFill
    contents:
    - id: CEKeyGuardArmory
    - id: CEKeyGuardHeadRoom
    - id: CEKeyGuardHall
    - id: CEKeyGuardStaff
