# Guard

- type: playTimeTracker
  id: CEJobGuardCommander

- type: playTimeTracker
  id: CEJobGuard

- type: playTimeTracker
  id: CEJobInvestigator

# Citizens

- type: playTimeTracker
  id: CEJobTownfolk

- type: playTimeTracker
  id: CEJobBard
