# Guard

- type: playTimeTracker
  id: CEJobGuardCommander

- type: playTimeTracker
  id: CEJobGuard

- type: playTimeTracker
  id: CEJobInvestigator

# Tavern

- type: playTimeTracker
  id: CEJobTavernmaster

- type: playTimeTracker
  id: CEJobBartender

- type: playTimeTracker
  id: CEJobChef

- type: playTimeTracker
  id: CEJobFarmer

# Citizens

- type: playTimeTracker
  id: CEJobTownfolk

- type: playTimeTracker
  id: CEJobBard

- type: playTimeTracker
  id: CEJobTailorMerchant

- type: playTimeTracker
  id: CEJobPharmacistMerchant

- type: playTimeTracker
  id: CEJobHomeGoodsMerchant
