- type: entity
  parent: BaseMindRoleAntag
  id: CEMindRoleVampire
  categories: [ ForkFiltered ]
  name: Vampire role
  components:
  - type: MindRole
    antagPrototype: CEVampire
    roleType: SoloAntagonist
    exclusiveAntag: true
  - type: CEVampireRole

- type: entity
  parent: BaseMindRoleAntag
  id: CEMindRoleThief
  categories: [ ForkFiltered ]
  name: Thief role
  components:
  - type: MindRole
    antagPrototype: CEThief
    roleType: SoloAntagonist
    exclusiveAntag: true
